### ISSUE TITLE
Subjecti deletemine

### ISSUE THREAD

**Issue by Caupz** [Caupz/SchoolBoy3000#16]
Andreas peab oma issue #15 enne ära tegema. 

SubjectPagel võiks olla hetkese ühe nupu asemel 2 nuppu. Ehk hetkel kui on raisedbutton > row > [extended, extended.... ], siis võiks olla et on row kus on kõrvuti 2 raisedbuttonit. Üks nupp on pikem kus on siis sarnaselt nagu praegu et semester, subject name ja õppejõunimi (ära weekdayd pane kuna Andreas peaks ära eemaldama weekday terve loogika subjectist kuna see selleks vale koht). Ja teine button on siis mingi trashiconiga või kui iconit ei saa siis pane textina X sinna.

Selle delete nupule vajutades siis eemaldatakse antud subject kanne ära. Tuleks eemaldada AppDB class'i kaudu delete funktsiooni kasutades ning ka "model.subjects" alt. Vb AppDB func ei tööta, pole testinud. Kui ei tööta siis kui ise ei oska parandada, siis anna teada ja uurin.

**Comment by andrikaljumae** [comment]
done
