### ISSUE TITLE
Readme.md korda teha 

### ISSUE THREAD

**Issue by Caupz** [Caupz/SchoolBoy3000#24]
Korrastada põhiliselt. Võiks teha ilusti mingid alapealkirjad panna, et oleks paremini eristatavad erinevad osad.

Lisaks võiks:

    Lisada juurde juhised kuidas rakendus allalaadida ja tööle panna.
    Lisada juurde mingi nimekiri asjadest milliseid pluginaid kasutame või mis versioone ning mis versioonide/emulaatorite peal testisime.
    Lisada juurde arendajate nimekiri.

Googeldada Readme.md how to make headings või mis iganes, et näha juhised kuidas mida teha.

**Comment by andrikaljumae** [comment]
.
